name: Build ICS for Pages

on:
  push:
    paths:
      - 'events.md'
      - 'generate-ics.js'
      - '.github/workflows/build-ics.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate ICS
        run: node generate-ics.js

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
